#pragma once

#define IOCTL_SHADOWMEM_REG_FATHER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1000, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SHADOWMEM_REG_CHILD CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1001, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SHADOWMEM_SAVE_BUFFERS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1002, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PREPARE_MAPPING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1003, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_TURN_ON_SHADOW_BASE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1004, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TURN_OFF_SHADOW_BASE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1005, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SHADOWMEM_STAT_SUCCESS 0x1337
#define SHADOWMEM_STAT_FAIL 0xDEAD